apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  imagePullSecrets:
  - name: dockercred
  containers:
  - name: zookeeper-node
    image: zookeeper
    ports:
    - containerPort: 2181
  containers:
  - name: drill-node1
    image: drill/apache-drill
    ports:
    - containerPort: 8047
  containers:
  - name: drill-node2
    image: drill/apache-drill
    ports:
    - containerPort: 8047